### ISSUE TITLE
Error running the package 

### ISSUE THREAD

**Issue by pavlo888** [oschwengers/platon#1]
Hi there, 

I have installed the Platon package to the best of my capabilities using Conda to crate an environment and then installing the dependencies using pip. 

However, when I try to run it using a draft genome assembly I obtain the following error

`Traceback (most recent call last):
  File "/usr/local/bin/platon", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/platon/platon.py", line 268, in main
    filtered_contigs = {k:v for (k,v) in scored_contigs.items() if filter_contig(v) }
  File "/usr/local/lib/python3.7/site-packages/platon/platon.py", line 268, in <dictcomp>
    filtered_contigs = {k:v for (k,v) in scored_contigs.items() if filter_contig(v) }
  File "/usr/local/lib/python3.7/site-packages/platon/functions.py", line 249, in filter_contig
    if( contig['is_circular'] ):
KeyError: 'is_circular'`

could you please help me fix this issue? 

Thanks in advance. 

Cheers, 
Pablo

**Comment by oschwengers** [comment]
Hi Pablo,
it seems that Platon has no circularity information for at least 1 contig. Are you sure to have `nucmer` from the `MUMmer` package installed, correctly?

I'm currently working on a complete Bioconda package for Platon which should fix all dependency versions. In addition I'm close to release a minor upgrade (v1.1.0) soon.

Maybe it's worth waiting for the upgrade if `nucmer` is not the source for your issue. 

Best regards,
Oliver

**Comment by pavlo888** [comment]
Hi Oliver,

Thank you for your reply. I have installed the Mummer package (which I
believe includes nucmer). However, when I try to run Platon on the command
line, it does not recognize my Fasta file. It says "file not recognized".

I will just wait for the upgrade and try it again.

Cheers,
Pablo

**Comment by oschwengers** [comment]
@pavlo888 I just released v1.1.0. So you can try this release with the new database: https://zenodo.org/record/3358926

Or you can try the new Bioconda package "platon" which is still 1.0.0, db: https://zenodo.org/record/3349652

Unfortunately, I'll be out of office the next 3 weeks, so please be patient. I hope this will fix this issue. If not, please provide some more information "--verbose" so I can debug it.

**Comment by pavlo888** [comment]
Hi @oschwengers, 

So I successfully installed the platon bioconda package and downloaded the db you sent; however, I get an error when running the command I get an error saying "is circular". Below you can find what the prompt shows: 

(platon) sam@BioInf2:~/Downloads$ platon --db db/ --verbose --output platon-test-1 '/media/sam/STOREPV/PVA_Assemblies_fasta/MAFF210265_JP.fasta' 
Options, parameters and arguments:
	db path: /home/sam/Downloads/db
	use bundled binaries: False
	genome path: /media/sam/STOREPV/PVA_Assemblies_fasta/MAFF210265_JP.fasta
	output path: /home/sam/Downloads/platon-test-1
	characterize: False
	tmp path: /tmp/tmpqq5n7gz6
	# threads: 8
parse draft genome...
	exclude contig 'scaffold49.1', too short (797)
	exclude contig 'scaffold50.1', too short (632)
	exclude contig 'scaffold51.1', too short (559)
	exclude contig 'scaffold52.1', too short (557)
	exclude contig 'scaffold53.1', too short (508)
	exclude contig 'scaffold54.1', too short (503)
	exclude contig 'scaffold55.1', too short (500)
predict ORFs...
	found 4927 ORFs
	removed 1 contig(s), no ORFs found
search marker proteins...
	found 384 marker proteins
score contigs...
prefilter contigs...
	excluded 0 contigs by min protein score threshold (-7.0)
analyze contigs...
Traceback (most recent call last):
  File "/home/sam/anaconda2/envs/platon/bin/platon", line 10, in <module>
    sys.exit(main())
  File "/home/sam/anaconda2/envs/platon/lib/python3.7/site-packages/platon/platon.py", line 257, in main
    filtered_contigs = {k: v for (k, v) in scored_contigs.items() if pf.filter_contig(v)}
  File "/home/sam/anaconda2/envs/platon/lib/python3.7/site-packages/platon/platon.py", line 257, in <dictcomp>
    filtered_contigs = {k: v for (k, v) in scored_contigs.items() if pf.filter_contig(v)}
  File "/home/sam/anaconda2/envs/platon/lib/python3.7/site-packages/platon/functions.py", line 260, in filter_contig
    if(contig['is_circular']):
KeyError: 'is_circular'

**Comment by oschwengers** [comment]
Hi @pavlo888 ,
I just checked the bioconda package version and I could reproduce the bug. I tested platon with mummer 4 but in the bioconda package mummer 3 was installed.
I updated the package and submitted a PR. 

In the meantime you could replace mummer3 by mumm4:
```bash
conda remove mummer
conda install mummer4
```
This fixed the issue for me. 
For some reasons, I had to reinstall biopython: ```conda install biopython```.
I hope this helps

**Comment by oschwengers** [comment]
Hi @pavlo888 ,
a PR fixing the wrong mummer version (3 instead of 4) has been accepted and the new bioconda package version is deployed.

A first test was successfully why I'll close this issue. If the error still exists, please reopen it.
Cheers!

**Comment by pavlo888** [comment]
Dear Oliver,

I just wanted to say THANKSSS!!!!! It has finally worked! Thank you so much
for your help!!!!

Best regards,
Pablo

**Comment by oschwengers** [comment]
@pavlo888 your welcome!
Glad to hear that everything works as expected.
