### ISSUE TITLE
Known plasmid genes detected in the chromosome

### ISSUE THREAD

**Issue by Clabe1986** [oschwengers/platon#11]
Hello,
This is not a technical issue. I successfully ran pluton 1.4 on Rhizobium genome. There are very well known symbiotic genes which usually lie on the symbiotic plasmid. However, I detected some of them on the chromosome and they were not present on the plasmid. I assembled the genome with spades. Is there anything wrong I am doing? I platon with default settings.

Clabe

**Comment by oschwengers** [comment]
Hello @Clabe1986 , as far as I can tell you are doing nothing wrong. So, if I understand you right, `platon` does not detect the contig harbouring these symbiotic genes as plasmid contigs?
This might simply be a false negative prediction. Platon uses precalculated plasmid/chromosome distribution ratios for many bacterial genes. Maybe either these symbiotic genes or some other up-/downstream genes are frequently encoded on the chromosome within the training data set of the last db (all RefSeq closed chromosomes and plasmids) so ´platon´ classifies this contig as chromosomal. Another issue could be that there is just not enough information on this contig, _i.e._ too few predicted or too many unknown genes.
If you can provide me with the assembly and some more information on the specific contigs and genes, I could take a closer look on this.

Best regards!

**Comment by Clabe1986** [comment]
Hello Oschwengers,
Thank you for the reply. Here I am attaching contigs files and annotated files so that you  can have a look at it. All the nif genes, nod genes and fix fines should appear on the symbiotic plasmid. I can see many fix genes, 3 nod genes and 1 nif gene on the chromosome.
[contigs.zip](https://github.com/oschwengers/platon/files/5010330/contigs.zip)

**Comment by oschwengers** [comment]
Hello @Clabe1986 ,
just coming back from vacation, so first of all sry for the late reply.
I glimpsed into your files which look OK, however, the Genbanks contain a single sequence only. Are these the same sequences as in the fasta files? Have these been concatenated somehow? Unfortunately, from the annotated files I cannot see on which contigs the aforementioned genes are encoded. Could you provide the annotations as multigenbanks per contig?

**Comment by Clabe1986** [comment]
Hello,
Sorry for the delayed response. I was very committed elsewhere. Actually the annot file contains a concatenated file. Let me annotate multi-contig file and send you tomorrow.

Thank you,
CW

**Comment by oschwengers** [comment]
Hello @Clabe1986 , long time no see... I'll close this for now. If this is still an issue, please do not hesitate to re-open it.
