### ISSUE TITLE
platon: error: unrecognized arguments: assembly.fasta

### ISSUE THREAD

**Issue by ZhangDengwei** [oschwengers/platon#14]
hi,

When performing the command according to the tutorial, I encountered an error. My command is 
```
platon -db /mnt/microbio_research/dengwei/database/platon_db/db/ assembly.fasta
```
And the error:

```
$ usage: platon [-h] [--db DB] [--mode {sensitivity,accuracy,specificity}]
              [--characterize] [--output OUTPUT] [--prefix PREFIX]
              [--threads THREADS] [--verbose] [--version]
              <genome>
platon: error: unrecognized arguments: assembly.fasta
```

May you kindly give any suggestion? Thanks in advance.

**Comment by ZhangDengwei** [comment]
my command was wrong, it should be 

```
platon --db /mnt/microbio_research/dengwei/database/platon_db/db/ assembly.fasta
```

**Comment by lisavader** [comment]
I had the same issue, there is a typo in the documentation.

`$ platon -db ~/db --output results/ --verbose --threads 8 genome.fasta`
should be
`$ platon --db ~/db --output results/ --verbose --threads 8 genome.fasta`

**Comment by oschwengers** [comment]
Thanks @ZhangDengwei for the issue and @lisavader for pointing out the typo - it's fixed, now: https://github.com/oschwengers/platon/commit/fa472970925822d07be2aeb9f272a2e413075806
