### ISSUE TITLE
ERROR: genome file not readable!

### ISSUE THREAD

**Issue by Dey497** [oschwengers/platon#15]
Hi,

First, thank you so much for creating and developing Platon.

I have an issue installing Platon. 
Indeed, using Conda/BioConda when I run the command: 
$ platon --db ./db genome.fasta

I have an error message:
ERROR: genome file (/home/administrateur/Platon/genome.fasta) not readable!
And when I check in the depository, I have no such file as genome.fasta 

Do you have any idea how to solve this issue? 

I'm using platon 1.5.0.

However, when I run:
$ platon --help
I have the help documentation. 

Thank you so much in advance for your much appreciated help!

Audrey

**Comment by Dey497** [comment]
I found the solution to my issue:

The path to the database was wrong. I found it using: 
$ pwd -P

and then:
platon --mode accuracy --output Platon_results --db /home/PATH/db genome.fasta

And now it works ... Sorry for my ignorance! 

Thank you again for Platon

**Comment by RightCake1** [comment]
Hi i'm getting that my genome fasta is unrecognized. What should i do?
