### ISSUE TITLE
Error occurs while trying to run Platon

### ISSUE THREAD

**Issue by Rajeefa** [oschwengers/platon#16]
Hi, 
I installed the dependencies as well as database but when am trying to run platon I get error like this :

platon --verbose --threads 4 Ecloacae4.fasta

Options, parameters and arguments:
	db path: /home/abb/platon/db
	use bundled binaries: True
	genome path: /home/abb/Ecloacae4.fasta
	output path: /home/abb
	prefix: Ecloacae4
	mode: accuracy
	characterize: False
	tmp path: /tmp/tmpga06u329
	# threads: 4
parse draft genome...
	exclude contig 'E.cloacae4_contig_55', too short (341)
	exclude contig 'E.cloacae4_contig_56', too short (227)
	exclude contig 'E.cloacae4_contig_57', too short (333)
	exclude contig 'E.cloacae4_contig_58', too short (590)
	exclude contig 'E.cloacae4_contig_63', too short (247)
	exclude contig 'E.cloacae4_contig_78', too short (307)
	exclude contig 'E.cloacae4_contig_80', too short (587)
	exclude contig 'E.cloacae4_contig_81', too short (739)
	exclude contig 'E.cloacae4_contig_84', too short (279)
	exclude contig 'E.cloacae4_contig_85', too short (448)
	exclude contig 'E.cloacae4_contig_88', too short (941)
	exclude contig 'E.cloacae4_contig_90', too short (474)
	exclude contig 'E.cloacae4_contig_91', too short (723)
	exclude contig 'E.cloacae4_contig_92', too short (535)
	exclude contig 'E.cloacae4_contig_93', too short (453)
	exclude contig 'E.cloacae4_contig_94', too short (412)
	exclude contig 'E.cloacae4_contig_95', too short (875)
	exclude contig 'E.cloacae4_contig_96', too short (875)
	exclude contig 'E.cloacae4_contig_98', too short (281)
	exclude contig 'E.cloacae4_contig_103', too short (914)
	exclude contig 'E.cloacae4_contig_104', too short (660)
	exclude contig 'E.cloacae4_contig_105', too short (374)
	exclude contig 'E.cloacae4_contig_106', too short (452)
	exclude contig 'E.cloacae4_contig_107', too short (401)
	exclude contig 'E.cloacae4_contig_108', too short (250)
	exclude contig 'E.cloacae4_contig_110', too short (532)
	exclude contig 'E.cloacae4_contig_112', too short (451)
	exclude contig 'E.cloacae4_contig_114', too short (922)
	exclude contig 'E.cloacae4_contig_116', too short (432)
	exclude contig 'E.cloacae4_contig_117', too short (209)
	exclude contig 'E.cloacae4_contig_118', too short (382)
	exclude contig 'E.cloacae4_contig_120', too short (520)
	exclude contig 'E.cloacae4_contig_121', too short (615)
	exclude contig 'E.cloacae4_contig_122', too short (313)
	exclude contig 'E.cloacae4_contig_123', too short (251)
	exclude contig 'E.cloacae4_contig_124', too short (221)
	exclude contig 'E.cloacae4_contig_125', too short (416)
	exclude contig 'E.cloacae4_contig_126', too short (305)
	exclude contig 'E.cloacae4_contig_128', too short (355)
	exclude contig 'E.cloacae4_contig_129', too short (251)
	exclude contig 'E.cloacae4_contig_130', too short (249)
	exclude contig 'E.cloacae4_contig_131', too short (565)
	exclude contig 'E.cloacae4_contig_132', too short (487)
	exclude contig 'E.cloacae4_contig_133', too short (220)
	exclude contig 'E.cloacae4_contig_134', too short (292)
	exclude contig 'E.cloacae4_contig_135', too short (271)
	exclude contig 'E.cloacae4_contig_136', too short (220)
	exclude contig 'E.cloacae4_contig_137', too short (221)
	exclude contig 'E.cloacae4_contig_138', too short (253)
	exclude contig 'E.cloacae4_contig_139', too short (323)
	exclude contig 'E.cloacae4_contig_140', too short (335)
	exclude contig 'E.cloacae4_contig_142', too short (346)
	exclude contig 'E.cloacae4_contig_144', too short (633)
	exclude contig 'E.cloacae4_contig_145', too short (314)
	exclude contig 'E.cloacae4_contig_146', too short (248)
	exclude contig 'E.cloacae4_contig_147', too short (223)
	exclude contig 'E.cloacae4_contig_148', too short (461)
	exclude contig 'E.cloacae4_contig_149', too short (857)
	exclude contig 'E.cloacae4_contig_150', too short (521)
	exclude contig 'E.cloacae4_contig_151', too short (311)
	exclude contig 'E.cloacae4_contig_152', too short (275)
	exclude contig 'E.cloacae4_contig_153', too short (240)
	exclude contig 'E.cloacae4_contig_154', too short (161)
	exclude contig 'E.cloacae4_contig_155', too short (174)
	exclude contig 'E.cloacae4_contig_156', too short (219)
	exclude contig 'E.cloacae4_contig_157', too short (244)
	exclude contig 'E.cloacae4_contig_158', too short (550)
	exclude contig 'E.cloacae4_contig_159', too short (252)
	exclude contig 'E.cloacae4_contig_160', too short (448)
	exclude contig 'E.cloacae4_contig_161', too short (223)
	exclude contig 'E.cloacae4_contig_162', too short (318)
	exclude contig 'E.cloacae4_contig_163', too short (311)
	exclude contig 'E.cloacae4_contig_164', too short (215)
	exclude contig 'E.cloacae4_contig_165', too short (220)
	exclude contig 'E.cloacae4_contig_166', too short (250)
	exclude contig 'E.cloacae4_contig_167', too short (256)
	exclude contig 'E.cloacae4_contig_168', too short (401)
	exclude contig 'E.cloacae4_contig_169', too short (251)
	exclude contig 'E.cloacae4_contig_170', too short (326)
	exclude contig 'E.cloacae4_contig_171', too short (424)
	exclude contig 'E.cloacae4_contig_172', too short (448)
	exclude contig 'E.cloacae4_contig_173', too short (365)
	exclude contig 'E.cloacae4_contig_174', too short (389)
	exclude contig 'E.cloacae4_contig_175', too short (259)
	exclude contig 'E.cloacae4_contig_176', too short (262)
	exclude contig 'E.cloacae4_contig_177', too short (325)
	exclude contig 'E.cloacae4_contig_178', too short (205)
	exclude contig 'E.cloacae4_contig_179', too short (299)
	exclude contig 'E.cloacae4_contig_180', too short (270)
	exclude contig 'E.cloacae4_contig_181', too short (233)
	exclude contig 'E.cloacae4_contig_182', too short (247)
	exclude contig 'E.cloacae4_contig_183', too short (347)
	exclude contig 'E.cloacae4_contig_184', too short (427)
	exclude contig 'E.cloacae4_contig_185', too short (248)
	exclude contig 'E.cloacae4_contig_186', too short (235)
	exclude contig 'E.cloacae4_contig_187', too short (263)
	exclude contig 'E.cloacae4_contig_188', too short (491)
	exclude contig 'E.cloacae4_contig_189', too short (257)
	exclude contig 'E.cloacae4_contig_190', too short (278)
	exclude contig 'E.cloacae4_contig_191', too short (309)
	exclude contig 'E.cloacae4_contig_192', too short (463)
	exclude contig 'E.cloacae4_contig_193', too short (233)
	exclude contig 'E.cloacae4_contig_194', too short (277)
	exclude contig 'E.cloacae4_contig_195', too short (402)
	exclude contig 'E.cloacae4_contig_196', too short (252)
	exclude contig 'E.cloacae4_contig_197', too short (399)
	exclude contig 'E.cloacae4_contig_198', too short (259)
	exclude contig 'E.cloacae4_contig_199', too short (219)
	exclude contig 'E.cloacae4_contig_200', too short (259)
	exclude contig 'E.cloacae4_contig_201', too short (494)
	exclude contig 'E.cloacae4_contig_202', too short (549)
	exclude contig 'E.cloacae4_contig_203', too short (249)
	exclude contig 'E.cloacae4_contig_204', too short (300)
	exclude contig 'E.cloacae4_contig_205', too short (252)
	exclude contig 'E.cloacae4_contig_206', too short (250)
	exclude contig 'E.cloacae4_contig_207', too short (379)
	exclude contig 'E.cloacae4_contig_208', too short (361)
	exclude contig 'E.cloacae4_contig_209', too short (175)
	exclude contig 'E.cloacae4_contig_210', too short (256)
	exclude contig 'E.cloacae4_contig_211', too short (586)
	exclude contig 'E.cloacae4_contig_212', too short (251)
	exclude contig 'E.cloacae4_contig_213', too short (413)
	exclude contig 'E.cloacae4_contig_214', too short (226)
	exclude contig 'E.cloacae4_contig_215', too short (411)
	exclude contig 'E.cloacae4_contig_216', too short (366)
	exclude contig 'E.cloacae4_contig_217', too short (432)
	exclude contig 'E.cloacae4_contig_218', too short (470)
	exclude contig 'E.cloacae4_contig_219', too short (251)
	exclude contig 'E.cloacae4_contig_220', too short (260)
	exclude contig 'E.cloacae4_contig_221', too short (236)
	exclude contig 'E.cloacae4_contig_222', too short (411)
	exclude contig 'E.cloacae4_contig_223', too short (251)
	exclude contig 'E.cloacae4_contig_224', too short (444)
	exclude contig 'E.cloacae4_contig_225', too short (247)
	exclude contig 'E.cloacae4_contig_226', too short (378)
	exclude contig 'E.cloacae4_contig_227', too short (251)
	exclude contig 'E.cloacae4_contig_228', too short (220)
	exclude contig 'E.cloacae4_contig_229', too short (470)
	exclude contig 'E.cloacae4_contig_230', too short (251)
	exclude contig 'E.cloacae4_contig_231', too short (434)
	exclude contig 'E.cloacae4_contig_232', too short (251)
	exclude contig 'E.cloacae4_contig_233', too short (251)
	exclude contig 'E.cloacae4_contig_234', too short (293)
	exclude contig 'E.cloacae4_contig_235', too short (248)
	exclude contig 'E.cloacae4_contig_236', too short (202)
	exclude contig 'E.cloacae4_contig_237', too short (250)
	exclude contig 'E.cloacae4_contig_238', too short (319)
	exclude contig 'E.cloacae4_contig_239', too short (251)
	exclude contig 'E.cloacae4_contig_240', too short (251)
	exclude contig 'E.cloacae4_contig_241', too short (465)
	exclude contig 'E.cloacae4_contig_242', too short (248)
	exclude contig 'E.cloacae4_contig_243', too short (314)
	exclude contig 'E.cloacae4_contig_244', too short (251)
	exclude contig 'E.cloacae4_contig_245', too short (267)
	exclude contig 'E.cloacae4_contig_246', too short (247)
	exclude contig 'E.cloacae4_contig_247', too short (251)
	exclude contig 'E.cloacae4_contig_248', too short (402)
	exclude contig 'E.cloacae4_contig_249', too short (423)
	exclude contig 'E.cloacae4_contig_250', too short (369)
	exclude contig 'E.cloacae4_contig_251', too short (310)
	exclude contig 'E.cloacae4_contig_252', too short (349)
	exclude contig 'E.cloacae4_contig_253', too short (208)
	exclude contig 'E.cloacae4_contig_254', too short (284)
	exclude contig 'E.cloacae4_contig_255', too short (41)
	exclude contig 'E.cloacae4_contig_256', too short (281)
	exclude contig 'E.cloacae4_contig_257', too short (249)
	exclude contig 'E.cloacae4_contig_258', too short (216)
	exclude contig 'E.cloacae4_contig_259', too short (229)
	exclude contig 'E.cloacae4_contig_260', too short (167)
	exclude contig 'E.cloacae4_contig_261', too short (285)
	exclude contig 'E.cloacae4_contig_262', too short (422)
	exclude contig 'E.cloacae4_contig_263', too short (263)
	exclude contig 'E.cloacae4_contig_264', too short (244)
	exclude contig 'E.cloacae4_contig_265', too short (250)
	exclude contig 'E.cloacae4_contig_266', too short (358)
	exclude contig 'E.cloacae4_contig_267', too short (251)
	exclude contig 'E.cloacae4_contig_268', too short (246)
	exclude contig 'E.cloacae4_contig_269', too short (312)
	exclude contig 'E.cloacae4_contig_270', too short (398)
	exclude contig 'E.cloacae4_contig_271', too short (251)
	exclude contig 'E.cloacae4_contig_272', too short (287)
	exclude contig 'E.cloacae4_contig_273', too short (245)
	exclude contig 'E.cloacae4_contig_274', too short (450)
	exclude contig 'E.cloacae4_contig_275', too short (437)
	exclude contig 'E.cloacae4_contig_276', too short (234)
	exclude contig 'E.cloacae4_contig_277', too short (250)
	exclude contig 'E.cloacae4_contig_278', too short (246)
	exclude contig 'E.cloacae4_contig_279', too short (250)
	exclude contig 'E.cloacae4_contig_280', too short (391)
	exclude contig 'E.cloacae4_contig_281', too short (251)
	exclude contig 'E.cloacae4_contig_282', too short (330)
	exclude contig 'E.cloacae4_contig_283', too short (404)
	exclude contig 'E.cloacae4_contig_284', too short (227)
	exclude contig 'E.cloacae4_contig_285', too short (440)
	exclude contig 'E.cloacae4_contig_286', too short (217)
	exclude contig 'E.cloacae4_contig_287', too short (339)
	exclude contig 'E.cloacae4_contig_288', too short (251)
	exclude contig 'E.cloacae4_contig_289', too short (250)
	exclude contig 'E.cloacae4_contig_290', too short (301)
	exclude contig 'E.cloacae4_contig_291', too short (237)
	exclude contig 'E.cloacae4_contig_292', too short (251)
	exclude contig 'E.cloacae4_contig_293', too short (358)
	exclude contig 'E.cloacae4_contig_294', too short (250)
	exclude contig 'E.cloacae4_contig_295', too short (251)
	exclude contig 'E.cloacae4_contig_296', too short (217)
	exclude contig 'E.cloacae4_contig_297', too short (282)
	exclude contig 'E.cloacae4_contig_298', too short (129)
	exclude contig 'E.cloacae4_contig_299', too short (515)
	exclude contig 'E.cloacae4_contig_300', too short (248)
	exclude contig 'E.cloacae4_contig_301', too short (266)
	exclude contig 'E.cloacae4_contig_302', too short (364)
	exclude contig 'E.cloacae4_contig_303', too short (282)
	exclude contig 'E.cloacae4_contig_304', too short (233)
	exclude contig 'E.cloacae4_contig_305', too short (251)
	exclude contig 'E.cloacae4_contig_306', too short (225)
	exclude contig 'E.cloacae4_contig_307', too short (303)
	exclude contig 'E.cloacae4_contig_308', too short (270)
	exclude contig 'E.cloacae4_contig_309', too short (372)
	exclude contig 'E.cloacae4_contig_310', too short (231)
	exclude contig 'E.cloacae4_contig_311', too short (396)
	exclude contig 'E.cloacae4_contig_312', too short (251)
	exclude contig 'E.cloacae4_contig_313', too short (247)
	exclude contig 'E.cloacae4_contig_314', too short (245)
	exclude contig 'E.cloacae4_contig_315', too short (258)
	exclude contig 'E.cloacae4_contig_316', too short (250)
	exclude contig 'E.cloacae4_contig_317', too short (229)
	exclude contig 'E.cloacae4_contig_318', too short (250)
	exclude contig 'E.cloacae4_contig_319', too short (239)
	exclude contig 'E.cloacae4_contig_320', too short (200)
	exclude contig 'E.cloacae4_contig_321', too short (364)
	exclude contig 'E.cloacae4_contig_322', too short (217)
	exclude contig 'E.cloacae4_contig_323', too short (251)
	exclude contig 'E.cloacae4_contig_324', too short (250)
	exclude contig 'E.cloacae4_contig_325', too short (251)
	exclude contig 'E.cloacae4_contig_326', too short (297)
	exclude contig 'E.cloacae4_contig_327', too short (207)
	exclude contig 'E.cloacae4_contig_328', too short (448)
	exclude contig 'E.cloacae4_contig_329', too short (202)
	exclude contig 'E.cloacae4_contig_330', too short (414)
	exclude contig 'E.cloacae4_contig_331', too short (250)
	exclude contig 'E.cloacae4_contig_332', too short (300)
	exclude contig 'E.cloacae4_contig_333', too short (229)
	exclude contig 'E.cloacae4_contig_334', too short (240)
	exclude contig 'E.cloacae4_contig_335', too short (206)
	exclude contig 'E.cloacae4_contig_336', too short (223)
	exclude contig 'E.cloacae4_contig_337', too short (394)
	exclude contig 'E.cloacae4_contig_338', too short (251)
	exclude contig 'E.cloacae4_contig_339', too short (228)
	exclude contig 'E.cloacae4_contig_340', too short (263)
	exclude contig 'E.cloacae4_contig_341', too short (445)
	exclude contig 'E.cloacae4_contig_342', too short (248)
	exclude contig 'E.cloacae4_contig_343', too short (267)
	exclude contig 'E.cloacae4_contig_344', too short (290)
	exclude contig 'E.cloacae4_contig_345', too short (250)
	exclude contig 'E.cloacae4_contig_346', too short (350)
	exclude contig 'E.cloacae4_contig_347', too short (297)
	exclude contig 'E.cloacae4_contig_348', too short (225)
	exclude contig 'E.cloacae4_contig_349', too short (252)
	exclude contig 'E.cloacae4_contig_350', too short (300)
	exclude contig 'E.cloacae4_contig_351', too short (251)
	exclude contig 'E.cloacae4_contig_352', too short (297)
	exclude contig 'E.cloacae4_contig_353', too short (312)
	exclude contig 'E.cloacae4_contig_354', too short (304)
	exclude contig 'E.cloacae4_contig_355', too short (235)
	exclude contig 'E.cloacae4_contig_356', too short (216)
	exclude contig 'E.cloacae4_contig_357', too short (209)
	exclude contig 'E.cloacae4_contig_358', too short (270)
	exclude contig 'E.cloacae4_contig_359', too short (328)
	exclude contig 'E.cloacae4_contig_360', too short (247)
	exclude contig 'E.cloacae4_contig_361', too short (252)
	exclude contig 'E.cloacae4_contig_362', too short (279)
	exclude contig 'E.cloacae4_contig_363', too short (245)
	exclude contig 'E.cloacae4_contig_364', too short (251)
	exclude contig 'E.cloacae4_contig_365', too short (250)
	exclude contig 'E.cloacae4_contig_366', too short (251)
	exclude contig 'E.cloacae4_contig_367', too short (376)
	exclude contig 'E.cloacae4_contig_368', too short (250)
	exclude contig 'E.cloacae4_contig_369', too short (248)
	exclude contig 'E.cloacae4_contig_370', too short (285)
	exclude contig 'E.cloacae4_contig_371', too short (251)
	exclude contig 'E.cloacae4_contig_372', too short (251)
	exclude contig 'E.cloacae4_contig_373', too short (568)
	exclude contig 'E.cloacae4_contig_374', too short (243)
	exclude contig 'E.cloacae4_contig_375', too short (235)
	exclude contig 'E.cloacae4_contig_376', too short (233)
	exclude contig 'E.cloacae4_contig_377', too short (248)
	exclude contig 'E.cloacae4_contig_378', too short (321)
	exclude contig 'E.cloacae4_contig_379', too short (412)
	exclude contig 'E.cloacae4_contig_380', too short (251)
	exclude contig 'E.cloacae4_contig_381', too short (250)
	exclude contig 'E.cloacae4_contig_382', too short (340)
	exclude contig 'E.cloacae4_contig_383', too short (415)
	exclude contig 'E.cloacae4_contig_384', too short (250)
	exclude contig 'E.cloacae4_contig_385', too short (236)
	exclude contig 'E.cloacae4_contig_386', too short (251)
	exclude contig 'E.cloacae4_contig_387', too short (251)
	exclude contig 'E.cloacae4_contig_388', too short (251)
	exclude contig 'E.cloacae4_contig_389', too short (251)
	exclude contig 'E.cloacae4_contig_390', too short (251)
	exclude contig 'E.cloacae4_contig_391', too short (259)
	exclude contig 'E.cloacae4_contig_392', too short (246)
	exclude contig 'E.cloacae4_contig_393', too short (244)
	exclude contig 'E.cloacae4_contig_394', too short (251)
	exclude contig 'E.cloacae4_contig_395', too short (248)
	exclude contig 'E.cloacae4_contig_396', too short (251)
	exclude contig 'E.cloacae4_contig_397', too short (258)
	exclude contig 'E.cloacae4_contig_398', too short (264)
	exclude contig 'E.cloacae4_contig_399', too short (250)
	exclude contig 'E.cloacae4_contig_400', too short (249)
	exclude contig 'E.cloacae4_contig_401', too short (332)
	exclude contig 'E.cloacae4_contig_402', too short (232)
	exclude contig 'E.cloacae4_contig_403', too short (328)
	exclude contig 'E.cloacae4_contig_404', too short (362)
	exclude contig 'E.cloacae4_contig_405', too short (310)
	exclude contig 'E.cloacae4_contig_406', too short (249)
	exclude contig 'E.cloacae4_contig_407', too short (245)
	exclude contig 'E.cloacae4_contig_408', too short (262)
	exclude contig 'E.cloacae4_contig_409', too short (248)
	exclude contig 'E.cloacae4_contig_410', too short (298)
	exclude contig 'E.cloacae4_contig_411', too short (230)
	exclude contig 'E.cloacae4_contig_412', too short (244)
	exclude contig 'E.cloacae4_contig_413', too short (296)
	exclude contig 'E.cloacae4_contig_414', too short (251)
	exclude contig 'E.cloacae4_contig_415', too short (201)
	exclude contig 'E.cloacae4_contig_416', too short (239)
	exclude contig 'E.cloacae4_contig_417', too short (387)
	exclude contig 'E.cloacae4_contig_418', too short (273)
	exclude contig 'E.cloacae4_contig_419', too short (257)
	exclude contig 'E.cloacae4_contig_420', too short (251)
	exclude contig 'E.cloacae4_contig_421', too short (284)
	exclude contig 'E.cloacae4_contig_422', too short (213)
	exclude contig 'E.cloacae4_contig_423', too short (231)
	exclude contig 'E.cloacae4_contig_424', too short (277)
	exclude contig 'E.cloacae4_contig_425', too short (251)
	exclude contig 'E.cloacae4_contig_426', too short (251)
	exclude contig 'E.cloacae4_contig_427', too short (251)
	exclude contig 'E.cloacae4_contig_428', too short (251)
	exclude contig 'E.cloacae4_contig_429', too short (251)
	exclude contig 'E.cloacae4_contig_430', too short (251)
	exclude contig 'E.cloacae4_contig_431', too short (251)
	exclude contig 'E.cloacae4_contig_432', too short (278)
	exclude contig 'E.cloacae4_contig_433', too short (251)
	exclude contig 'E.cloacae4_contig_434', too short (251)
	exclude contig 'E.cloacae4_contig_435', too short (242)
	exclude contig 'E.cloacae4_contig_436', too short (271)
	exclude contig 'E.cloacae4_contig_437', too short (250)
	exclude contig 'E.cloacae4_contig_438', too short (251)
	exclude contig 'E.cloacae4_contig_439', too short (251)
	exclude contig 'E.cloacae4_contig_440', too short (226)
	exclude contig 'E.cloacae4_contig_441', too short (247)
	exclude contig 'E.cloacae4_contig_442', too short (251)
	exclude contig 'E.cloacae4_contig_443', too short (294)
	exclude contig 'E.cloacae4_contig_444', too short (222)
	exclude contig 'E.cloacae4_contig_445', too short (324)
	exclude contig 'E.cloacae4_contig_446', too short (251)
	exclude contig 'E.cloacae4_contig_447', too short (251)
	exclude contig 'E.cloacae4_contig_448', too short (262)
	exclude contig 'E.cloacae4_contig_449', too short (226)
	exclude contig 'E.cloacae4_contig_450', too short (222)
	exclude contig 'E.cloacae4_contig_451', too short (210)
	exclude contig 'E.cloacae4_contig_452', too short (213)
	exclude contig 'E.cloacae4_contig_453', too short (311)
	exclude contig 'E.cloacae4_contig_454', too short (205)
	exclude contig 'E.cloacae4_contig_455', too short (249)
	exclude contig 'E.cloacae4_contig_456', too short (205)
	exclude contig 'E.cloacae4_contig_457', too short (222)
	exclude contig 'E.cloacae4_contig_458', too short (353)
	exclude contig 'E.cloacae4_contig_459', too short (246)
	exclude contig 'E.cloacae4_contig_460', too short (214)
	exclude contig 'E.cloacae4_contig_461', too short (211)
	exclude contig 'E.cloacae4_contig_462', too short (249)
	exclude contig 'E.cloacae4_contig_463', too short (206)
	exclude contig 'E.cloacae4_contig_464', too short (265)
	exclude contig 'E.cloacae4_contig_465', too short (251)
	exclude contig 'E.cloacae4_contig_466', too short (251)
	exclude contig 'E.cloacae4_contig_467', too short (258)
	exclude contig 'E.cloacae4_contig_468', too short (243)
	exclude contig 'E.cloacae4_contig_469', too short (248)
	exclude contig 'E.cloacae4_contig_470', too short (222)
	exclude contig 'E.cloacae4_contig_471', too short (222)
	exclude contig 'E.cloacae4_contig_472', too short (230)
	exclude contig 'E.cloacae4_contig_473', too short (64)
	exclude contig 'E.cloacae4_contig_474', too short (127)
	exclude contig 'E.cloacae4_contig_475', too short (164)
	exclude contig 'E.cloacae4_contig_476', too short (158)
	exclude contig 'E.cloacae4_contig_477', too short (397)
	exclude contig 'E.cloacae4_contig_478', too short (147)
	exclude contig 'E.cloacae4_contig_479', too short (220)
	exclude contig 'E.cloacae4_contig_480', too short (306)
	exclude contig 'E.cloacae4_contig_481', too short (178)
	parsed 481 raw contigs
	excluded 390 contigs by size filter
	analyze 91 contigs
predict ORFs...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/abb/platon/platon/platon.py", line 402, in <module>
    main()
  File "/home/abb/platon/platon/platon.py", line 178, in main
    proteins_path = pf.predict_orfs(config, contigs, genome_path)
  File "/home/abb/platon/platon/functions.py", line 501, in predict_orfs
    orf_id = cols[8].split(';')[0].split('=')[1].split('_')[1]
IndexError: list index out of range

Please help me with a solution to solve this out. 
Thanks

**Comment by oschwengers** [comment]
Hi @Rajeefa , sure, I need some more information:
- how did you install platon: `GitHub`, `PyPI` or `Conda`
- which version of Platon do you use?
And could you please attach the log file?

**Comment by Rajeefa** [comment]
I installed Platon 1.5.0 from Github using clone and also installed the required python dependencies and packages mentioned for the Platon .My contigs are assembled using CLC Genomics Workbench.
[Ecloacae4.log](https://github.com/oschwengers/platon/files/5764158/Ecloacae4.log)

**Comment by oschwengers** [comment]
Unfortunately, I cannot reproduce this error. Could you make sure, that `Prodigal` is working correctly by manually executing it:
```bash
<platon-dir>/share/prodigal -i Ecloacae4.fasta -a proteins.faa -c -f gff -o out.gff
```

You could also try to install platon via `BioConda`. Alternatively, you could also provide my with the genome so I could try to reproduce this with the original data - if this is possible.

**Comment by oschwengers** [comment]
Hi @Rajeefa any progress? Have you tried Prodigal? Or have you tried to install Platon via BioConda?

**Comment by Rajeefa** [comment]
Hi,
Yes I tried Prodigal it's working. The problem remains the same while trying to run Platon. Can I sent the genomes to get analysed. Only two isolates are there.I haven't tried installing Platon via BioConda because earlier once  my system got messed up while trying to install other software through BioConda.

**Comment by oschwengers** [comment]
Hi @Rajeefa ,
sure - please upload your files to `https://jlubox.uni-giessen.de/files/MlhTRGJjTTFWaHNQaUVMNnZ6R1JR` and let me know once the upload is finished.

**Comment by Rajeefa** [comment]
Hi ,
Sorry for the late reply . I can't upload files into the given link. I have been trying it since last week. Iam adding the fasta files into this as text files. I can also upload if there is another link.
[E.hormaechei2.txt](https://github.com/oschwengers/platon/files/6055431/E.hormaechei2.txt)

[E.hormaechei4.txt](https://github.com/oschwengers/platon/files/6055444/E.hormaechei4.txt)

**Comment by oschwengers** [comment]
Hi,
thank for the files. However, I still cannot reproduce the error. Both files were analyzed as expected. I attached the results for both genomes: 
[results.tar.gz](https://github.com/oschwengers/platon/files/6068923/results.tar.gz)

**Comment by Rajeefa** [comment]
Hi,
Thankyou for the results.
