### ISSUE TITLE
result are all plasmids

### ISSUE THREAD

**Issue by Wanli-HE** [oschwengers/platon#17]
HI!

when i using platon to predict plasmid contigs, the command is like below:
 "platon {input.f} --db {params.db} --mode {params.mode} -c -o {output.f} -t {threads} -v 2>{log.err} >{log.out}"

and i checked the result, in the * .plasmid.fasta file, is all contigs,  which  means all contig are been classified as plasmid. so what was happend?

no matter what kind of mode (Accuracy or Sensitivity).   and the version is platon 1.4.0.

**Comment by oschwengers** [comment]
Hello @Wanli-HE , thanks for your report.
In your command line you included the `-c` flag which activates the *characterization* mode so *all* filters will be deactivated.
`--characterize, -c    deactivate filters; characterize all contigs`
We introduced this to be able to run all contig characterizations all contigs. Just leave out the `-c` and the non-contigs should be left out from the `*.plasmid.fna` file.

I hope that helps.

**Comment by oschwengers** [comment]
Hi, I hope this answers your question. I'll close this for now. Please, feel free to re-open it.
