### ISSUE TITLE
Should all plasmids really have OriT sequences?

### ISSUE THREAD

**Issue by KTbiotech** [oschwengers/platon#18]
What should I do when the platon cannot identify OriT from the closed plasmid? Should all plasmids really have OriT sequences?

**Comment by oschwengers** [comment]
Hi, only mobilizable and conjugative plasmids should encode an oriT. So either your plasmids are non-mobilizable/non-conjugative or they encode unknown oriT sequences. You could crosscheck this via mob-suite, for instance.

**Comment by oschwengers** [comment]
Hi, I hope this answeres your question. I'll close this for now. Please, feel free to re-open it.
