### ISSUE TITLE
Plasmid verification

### ISSUE THREAD

**Issue by Handymanalan** [oschwengers/platon#19]
Hi Oliver,

Thanks for developing Platon, it's really handy. Do you know if there's anyway I can have do a quality check on the results? Something like CheckM that can check the quality of assembled genomes, is there a way I can verify if the results are high quality plasmids?

Cheers

Alan

**Comment by oschwengers** [comment]
Thanks @Handymanalan ,
Platon was designed to detect & characterize contigs resulting from (short-read) draft assemblies. It's not designed to detect entire plasmids. Hence, I'm not quite sure If I correctly understood your question or if it is pointing in the right direction.

`...results are high quality plasmids?` -> results are detected contigs which might be (part of) a plasmid.

To hopefully provide you with some more help here, could you please elaborate a little bit more on your use case and question? 
Best regards!

**Comment by Handymanalan** [comment]
Thanks Oliver,

Since `results are detected contigs which might be (part of) a plasmid.` Is there a way to check if there's non-plasmid contigs in the results?

Cheers

Alan

**Comment by oschwengers** [comment]
Of course, for example, you could cross-check Platon results for integrated conjugative elements (ICEs) or phages. These are prominent sources for false-positives.

**Comment by oschwengers** [comment]
I hope your question is answered. I'll close this issue for now. Just in case you have more questions, please do not hesitate to reopen it.
