### ISSUE TITLE
Issue updating Platon v1.6

### ISSUE THREAD

**Issue by Dey497** [oschwengers/platon#20]
**Describe the bug**
To help users and fix any bugs and issues a concise description if beneficial and often necessary.

Therefore, please provide us with at least the following information:
- what exactly happened
- what exact command was executed: just copy-paste the command line
- what installation of Platon did you use: `BioConda`, `GitHub`, `Pip`
- which version of Platon was used

**Comment by Dey497** [comment]
Hi, thank you so much for creating Platon !
I am just having an issue updating Platon v1.5 to v1.6. I re-dowloaded it as well as the database but when I type : 
>platon --version 
it still shows v1.5

Can you help me on how to have the up to date version of Platon, please?

Thank you in advance,
Audrey

**Comment by oschwengers** [comment]
Hi, which packaging system did you use? Conda or pip? Or have you downloaded the github repo?

**Comment by oschwengers** [comment]
Just in case your using Conda, please try: `conda install -c conda-forge -c bioconda platon=1.6`

**Comment by Dey497** [comment]
Hi, I tried as you suggested using Conda and it worked perfectly, thank you so much!
Audrey
