### ISSUE TITLE
ERROR: database file (orit.nhr) not readable!

### ISSUE THREAD

**Issue by alexlevylab** [oschwengers/platon#22]
Hello,

I tried to run platon by cloning it from github (v1.6). I downloaded the lastest database (v1.5.0).

When trying to run the command:
`platon --db /platon/db --prefix t --output test fasta.fna
`
I received the following error:  

`"ERROR: database file (orit.nhr) not readable!"`

I can see in the github /test/db/ file, there are the following database names:

- conjugation
- inc-types
- mobilization
- mps
- ncbifam-amr
- orit
- refseq-plasmids
- replication
- rRNA

This includes the missing "orit" database the error mentions.

However, the database v1.5.0, the latest, does not seem to have the orit part, but has these:

- conjugation
- inc-types
- mobilization
- ncbifam-amr
- protein-scores
- refseq-bacteria-nrpc-reps_0
- refseq-bacteria-nrpc-reps
- refseq-plasmids
- replication
- rRNA

I had the same issue with the bioconda version...

I would love to use and cite the tool, but I am having trouble with it. Please let me know if you have any idea how to fix this issue.

Thanks,

Alex

**Comment by oschwengers** [comment]
Hello @alexlevylab , I tried to reproduce the error but everything worked fine as expected. Also, the latest db file hosted on Zenodo does contain the `oriT` blast databases.

Could you please check again, that platon version `v1.6` is installed and version `v1.5.0` of the database is downloaded and in place?

I checked it via this set of commands:
```bash
conda create -p conda-test -c conda-forge -c bioconda platon=1.6
conda activate conda-test
platon --version
wget https://zenodo.org/record/4066768/files/db.tar.gz
tar -xvzf db.tar.gz
platon --db db/ -v <an-arbitrary-test-draft-assembly>
```

Best regards

**Comment by alexlevylab** [comment]
I was able to run it with conda, I must have made a mistake with the download of the db.

Thank you for your help!
