### ISSUE TITLE
Running multiple samples

### ISSUE THREAD

**Issue by mmfacun** [oschwengers/platon#23]
Hello. I tried running draft genome assemblies of multiple samples (different isolates) using the following code:

`for D in fasta_aba/ic2/*.fasta; do N=$(basename $D .fasta) ; platon --db db --output platon --prefix $N $D; done`

The outputs are for individual isolates. I have 500+ isolates and I don't think I can check every single one of them.

1. Is there any way to summarize the results in a single csv or tsv file? (i.e. presence/absence of plasmids, with corresponding %id and coverage; no. of plasmids detected per isolate; etc.)

2. is it possible to put the identity of plasmid hits in the current tsv output? current output is only no. of plasmid hits. 

Thank you

**Comment by oschwengers** [comment]
Hi. Yes, in theory that's possible. You could write a simple Python/Perl script to gather the results.
However, Platon works contig based and all results (each single line) are the results for a distinct contig within an assembly. Platon was designed to distinguish plasmid-borne from chromosome-borne contigs.

We're working on a new tool that addresses this use case but it's currently still work in progress. I'm sorry that I cannot provide more help right now on this side.

**Comment by mmfacun** [comment]
Hi again. Sorry but i'm really new at doing bioinfo and coding (i can't write scripts) and can't really work well with json files. Is there any way i can convert these results to tsv or csv format?

Thank you so much.
