### ISSUE TITLE
Differences between .log and plasmid.fasta file

### ISSUE THREAD

**Issue by tthye1** [oschwengers/platon#29]
Dear Oliver,

I have a similiar problem as xuanji2017. I analysed isolates harbouring the large pESI plasmid (CP016413). 
When I grep for the specific plasmid ID 'CP016413' in the .log file I got 42 hits but only 39 sequences appear in the plasmid.fasta file. As an example sequence contig00080, which fits perfectly to the pESI plasmid did not appear in the plasmid.fasta file.

 Do you have an idea where the discrepancies might come from?
I used platon version 1.6.

I attached the assembly file.

Best wishes,

Thorsten
[P8_contigs.txt](https://github.com/oschwengers/platon/files/7814814/P8_contigs.txt)
[P8_S17__out.1.contigs.txt](https://github.com/oschwengers/platon/files/7814895/P8_S17__out.1.contigs.txt)
[P8_S17__out.1.contigs.log](https://github.com/oschwengers/platon/files/7814896/P8_S17__out.1.contigs.log)
[P8_S17__out.1.contigs.plasmid.txt](https://github.com/oschwengers/platon/files/7814899/P8_S17__out.1.contigs.plasmid.txt)

**Comment by tthye1** [comment]
Hi,
Thanks for clarification. I will test the different modes.  But I wonder why not always include all contigs with an almost 100% identity to plasmids of the corresponding database to the results?

Best,

Thorsten

**Comment by oschwengers** [comment]
There are genomic islands that are frequently found on both chromosomes and plasmids, as for instance ICEs. Therefore, a plasmid hit alone is not sufficient for a contig classification as it could also be an ICE within a chromosome.
