### ISSUE TITLE
Platon report Mobilization and Conjugation

### ISSUE THREAD

**Issue by elina2410** [oschwengers/platon#34]
Hello everyone!

In the report, obtained from PLATON, I have columns named Mobilization and Conjugation.
In the #Mobilization column, I have 1 or 0 results, which I assume means 1-mobilizable 0- non-mobilizable.
Whereas in Column Conjugation I have many different numbers like 0, 4, 15,16, etc. What does mean? How to interpret these results. I could not find any hints in the manual. 
How interpret result below:
1. #Mobilization 1, #Conjugation 16 
2. #Mobilization 0 #Conjugation 2
3. #Mobilization 1 #Conjugation 0

I ask for help

**Comment by oschwengers** [comment]
Hi @elina2410,
It's simply the number of detected genes within these categories.

So in your case, Platon detected 
1. 1 mobilization gene & 16 conjugation genes
2. 0 mob. genes & 2 con. genes
3. 1 mob. gene & 0 con. genes

Best regards!

**Comment by elina2410** [comment]
so simple.. thanks for your immediate answer!
Best regards!
