### ISSUE TITLE
IndexError: list index out of range error

### ISSUE THREAD

**Issue by hbucqp** [oschwengers/platon#35]
Hi, 
I am trying to use Platon 1.6 installed with BioConda to identify plasmid contigs. By running the following command:

```
platon --db ~/database/db --prefix test --output ./ test.fa
```

Platon reports a **IndexError: list index out of range**

```
Traceback (most recent call last):
  File "/home/cui/miniconda3/envs/platon/bin/platon", line 10, in <module>
    sys.exit(main())
  File "/home/cui/miniconda3/envs/platon/lib/python3.8/site-packages/platon/platon.py", line 153, in main
    proteins_path = pf.predict_orfs(contigs, cfg.genome_path)
  File "/home/cui/miniconda3/envs/platon/lib/python3.8/site-packages/platon/functions.py", line 492, in predict_orfs
    orf_id = cols[8].split(';')[0].split('=')[1].split('_')[1]
IndexError: list index out of range
```
The version of dependent software is
- Prodigal: V2.6.3
- diamond: V2.0.15
- blastn: V2.13.0+
- hmmsearch: V3.3.2
- nucmer: V4.0.0
- cmscan: V1.1.4

The fasta file I used is [test.zip](https://github.com/oschwengers/platon/files/9191370/test.zip)

**Comment by oschwengers** [comment]
Hi @hbucqp,
there are `\r` (carriage return) characters in your fasta headers which might be introduced via a Windows-based text editor?
If you remove those, Platon works as expected. There are 6 plasmid predicted contigs in your data. Please find a filtered fasta file below:
[test.fna.gz](https://github.com/oschwengers/platon/files/9243169/test.fna.gz)

Best regards!
