### ISSUE TITLE
genome fasta file UNRECOGNIZED

### ISSUE THREAD

**Issue by RightCake1** [oschwengers/platon#36]
Hello so I have been trying for hours now. 
I keep running into this issue where my genome.fasta file is not being recognized

code i used - 
platon --db /media/mustafa/New Volume/Platon/db --output Platon_results/ --verbose --threads 8 M01094-002.fasta

I am not sure where my mistake is being made. Please help !

**Comment by RightCake1** [comment]
Sorry i might have added the wrong label

**Comment by oschwengers** [comment]
Hi @RightCake1 , I'm sorry for this very late reply. I hope you've somehow solved this, already. Just in case, you have a white space in the path that you've provided as `--db` parameter at `.../New Volume/...`. This is not possible on UNIX systems as this will be interpreted as 2 distinct parameters. Either you quote the white space or (and this is highly recommended) you do not use paths with white spaces.
Best regards

**Comment by RightCake1** [comment]
Yes i was able to solve the issue by reinstalling it in an environment. But Thank you for the solution as I'll be trying it the way you recommended. Best regards!

**Comment by RightCake1** [comment]
@oschwengers

**Comment by oschwengers** [comment]
Glad you could solve this, so I'll close this for now. Please, do not hesitate to re-open it in any case.
Best regards!
