### ISSUE TITLE
database file (rds.tsv) not readable

### ISSUE THREAD

**Issue by Lneffe** [oschwengers/platon#4]
Hi,

I tried to use platon 1.1.0, which I installed under a new conda environment with python 3.5. 
When trying to start the first analysis I encoutered the following error message: 

`ERROR: database file (rds.tsv) not readable!`

The db folder is in the platon folder, but I also gave the absoulte path of the db when trying to run the program. 
Additionally I wanted to change the permissions on the folder, but that didn´t work neither.

How can this be fixed?

Best wishes,
Lisa

**Comment by Aliceall** [comment]
Hi! 
Is the zenodo link to the database not working because of this issue?
Thank you for developing this tool btw!
Looking forward to use it.
Best

**Comment by oschwengers** [comment]
Hi @Lneffe , @Aliceall ,
thanks for using Platon. May I ask which database version you downloaded and use? I think there might be a mismatch between the  installed Platon version  (v1.1.0) and the database version.

We introduced some major changes in v1.2.0 which is not compatible with older database versions.

I highly recommend to update both (tool & db) to the latest versions, *.i.e.* **v1.3.1** and https://zenodo.org/record/3751774 since we made some major improvements.
Best regards!

**Comment by Lneffe** [comment]
Hello!

Thank you for the advice. 
It seems that I am not able to update the platon tool using the command
`conda update platon`
in the specific environment that I created for platon. 
I also tried deinstalling the version and running again
`conda install -c conda-forge -c bioconda -c defaults platon` 
but ended up with version 1.1. still.

How can I get version 1.3.1 via the conda channel? 
I am working in a shared server environment and do not have permissions for pip/github installation. 

Many thanks in advance,
looking forward to use the promising tool!

**Comment by oschwengers** [comment]
Hello @Lneffe , 
unfortunately, I cannot reproduce this error. I'm also using conda 4.8.3 and `conda install -c conda-forge -c bioconda -c defaults platon` in a fresh environment works as expected ending in a working platon v1.3.1 installation. Maybe there is a wrong configuration in your conda setup/channels? 

If you do not have `sudo` priviledges on your system, you could also try pip with the **--user** option together with `git clone`?
```
git clone git@github.com:oschwengers/platon.git
cd platon
python3 -m pip install --user platon
```

**Comment by Lneffe** [comment]
Hello @oschwengers !
The issue was with the python version and conda configuration.
I now used python version 3.8.3 in a completly new environment and installed the the tool incl. database. 
A first test run was succesfully completed as well.

Best regards!

**Comment by oschwengers** [comment]
You're welcome, nice that it's working, now.
Best regards!

**Comment by Aliceall** [comment]
Thank you @oschwengers!
I have conda 4.8.3, python 3.7, platon 1.3.1
I have installed everything following your instructions but when I get to this: platon --db ./db genome.fasta
it says is not readable.
Am I doing something wrong?
Thank you!

**Comment by oschwengers** [comment]
Hi @Aliceall ,
ok, just to go through this step by step:
1. You're able to execute `platon --help` without any errors?
2. Did you use an existing assembly in fasta format instead of just `genome.fasta`?

If yes, could you then please execute platon with the `--verbose` flag, open a new issue (as I guess this might be unrelated to the initial issue) and provide me with the resulting log file, so I can check the details?
Thanks and best regards!

**Comment by Aliceall** [comment]
Thank you.
the help message executes without errors. I hadn't try to run anything yet, I was just installing and following your steps. I will try now with my spades assembly and let you know how it goes.
Thanks

**Comment by Aliceall** [comment]
It worked perfectly!
thank you very much! Have a great day

**Comment by oschwengers** [comment]
Nice, you're welcome!
Best regards!

**Comment by Aliceall** [comment]
I have another question, very naive one. This is my first time with
plasmids.
I ran platon and now I know it found 2 plasmid 1 circular and one non
circular.
When I would like to know the function of these plasmids, would I look into
the file that is called contigs?
On those files I found a list, some discarded and some that say hit!
So then I looked into what they are, they are encoded by function, AMRs,
conjunction etc..
Then there is a combination of letters and numbers. Is this the references
in the database?
I recognized some of them, and found them on NCBI, but for many of them I
have no idea.
I tried looking for those (i.e. PCLA_3224486) but can't really understand
where are they coming from.
I paste here an example:

2020-06-02 11:30:27,651 - functions - INFO - conj genes: hit!
contig=NODE_9_length_115084_cov_64.723357, type=conjugation_PCLA_3224486,
start=97212, end=99104, strand=-

Any suggestion on how to go about this?

Thank you again for your time and for developing this tool.

Best regards

**Comment by oschwengers** [comment]
Hi @Aliceall ,
I'm not quite sure which file you mean by "called contigs". Platon writes 5 distinct files:
 - "<_prefix_>**.chromosome.fasta**": all contigs classified as chromosomal
 - "<_prefix_>**.plasmid.fasta**": all contigs classified as plasmid-born
 - "<_prefix_>**.tsv**": a tab-separated file copying the STDOUT
 - "<_prefix_>**.json**": a JSON file containing all results
 - "<_prefix_>**.log**": a log file with detailed (internal) information - mainly for debugging purposes

The PCLA_* numbers are identifiers from the NCBI prokaryotic proteins clusters: https://www.ncbi.nlm.nih.gov/proteinclusters/browse

Your specific PCLA hit for PCLA_3224486 refers to the _traN_ gene: https://www.ncbi.nlm.nih.gov/proteinclusters/?term=PCLA_3224486

The main application for Platon is to separate plamid-borne from chromosomal contigs for further analysis. An overview on the plasmid-borne contigs is printed to STDOUT and the <_prefix_>**.tsv** file. The <_prefix_>**.json** file contains all detailed information in a machine readable format.

I hope I could clarify your questions. Please, do not hesitate to keep asking if you have any further questions - but may I kindly ask you to open a new dedicated issue as the initial problem of this one is solved?
