### ISSUE TITLE
diamond version

### ISSUE THREAD

**Issue by Dabiguina94** [oschwengers/platon#43]
I cannot used platon because of the diamond version required, which is v2.0.14.
Initially I downloaded the newest version of Diamond v.2.1.8 and I had no problem with the installation,
and platon still insist with the v2.0.14, I downloaded but I couldn't install it.
So, any suggestions for the v2.0.14 installation? or how can I solve this issue?

Thank you

**Comment by oschwengers** [comment]
Hi, have you installed both Platon and Diamond in the same Conda environment?
A quick test using a fresh Conda environment with Platon 1.7 and Diamond 2.1.8 worked as expected:

```
mamba create -p ./platon-test-env platon
mamba activate ./platon-test-env
platon --db ./path/to/database --verbose test-genome.fna
```

**Comment by oschwengers** [comment]
Is this still active @Dabiguina94 ?
