### ISSUE TITLE
Platon for long-read contigs?

### ISSUE THREAD

**Issue by ranitori** [oschwengers/platon#47]
Hi,
I have sequenced multiple bacterial isolates with nanopore sequencing, and therefore after assembly generally obtained anywhere from 1 to 6 contigs per isolate. One of these contigs is usually the chromosome (3 - 9Mb) and some smaller contigs in the 1x10E3 to 1x10E5 kb range. I'm wondering whether platon is suitable for analysing the sequence data from a single bacterial isolate? To determine whether the smaller contigs (usually only 1 to 5 of them) are plasmids.
Thanks

**Comment by oschwengers** [comment]
Hi @ranitori ,
yes, Platon was designed to answer that specific question. However, we designed it to analyze short read-sequenced draft genomes but as Platon strictly works on contigs, it doesn't matter if these were assembled from short or long reads.

Obviously, larger contigs from long reads (or even complete plasmids) are much easier to classify as plasmids.

**Comment by ranitori** [comment]
Thanks for your quick reply!
