### ISSUE TITLE
Allow specification of output file prefix (not just path)

### ISSUE THREAD

**Issue by crarlus** [oschwengers/platon#7]
Hi,
I would like to be able to specify not only the output directory but also the prefix of the output files. The reason is that I am using platon in a snakemake workflow and I would like to assign the proper sample name even though the contig name might just be contig.fasta.

Do you think that is possible?

Thanks,
Carlus

**Comment by oschwengers** [comment]
Hi @crarlus ,
thanks for the hint. That should not be a problem.
I'll add a `--prefix` parameter soon and release a new version along with the fix for your #6 issue - maybe this week.

Best regards!

**Comment by oschwengers** [comment]
Hi @crarlus ,
I just pushed a new commit (ef15ac2) introducing a `--prefix <prefix>` option. By this, a prefix for all created files can be set:
- `<prefix>`.log
- `<prefix>`.chromosome.fasta
- `<prefix>`.plasmid.fasta
- `<prefix>`.json
- `<prefix>`.tsv

I'll wait with a new release to conduct some more tests on this but feel free to use this git head via git pull as described in the [readme](https://github.com/oschwengers/platon/blob/master/README.md) and please, let me know your feedback.
Best regards!

**Comment by oschwengers** [comment]
@crarlus I've implemented this new feature and will close this issue. Please feel free to reopen this or a new one just in case...
