### ISSUE TITLE
Platon can not get ORF id

### ISSUE THREAD

**Issue by chen1i6c04** [oschwengers/platon#8]
Hi 
I have installed Platon v1.3.1 by pip and run it using a genome assembly
I got below error message.
```
Traceback (most recent call last):
  File "/home/chen1i6c04/miniconda3/envs/py38/bin/platon", line 8, in <module>
    sys.exit(main())
  File "/home/chen1i6c04/miniconda3/envs/py38/lib/python3.8/site-packages/platon/platon.py", line 171, in main
    proteins_path = pf.predict_orfs(config, contigs, genome_path)
  File "/home/chen1i6c04/miniconda3/envs/py38/lib/python3.8/site-packages/platon/functions.py", line 501, in predict_orfs
    orf_id = cols[8].split(';')[0].split('=')[1].split('_')[1]
IndexError: list index out of range
```
This error happened seemingly in Platon parse the ORF id in gff file.
Did i do wrong something?

Thanks

**Comment by oschwengers** [comment]
Hi @chen1i6c04 ,
thanks for the report. Could you please execute Platon in `--verbose` mode and provide me the log file produced by Platon and if possible the input fasta file?
Have you tried the bioconda version? If not, coud you please try this or post the Prodigal-Version your using?

**Comment by chen1i6c04** [comment]
Hi @oschwengers 
My prodigal version is 2.6.3
and attach input fasta file, log file and prodigal gff file
hope they will help
[platon.log](https://github.com/oschwengers/platon/files/4844155/platon.log)
[fasta.fa](https://github.com/oschwengers/platon/files/4844161/R15.0599.txt)
[prodigal.gff](https://github.com/oschwengers/platon/files/4844165/prodigal.txt)

**Comment by oschwengers** [comment]
Hi @chen1i6c04 ,
I found the reason for this error. The fasta file you provided contains Windows `^M` (carriage return) characters which are not common on linux systems on/for which platon has been developed. You simply have to remove these carriage returns and everything is back to normal.

On linux, you can do this via: `sed $'s/\r//' R15.0599.txt > R15.0599.clean.txt`

On this cleaned file you get the following results:
```
ID	Length	Coverage	# ORFs	RDS	Circular	Inc Type(s)	# Replication	# Mobilization	# OriT	# Conjugation	# AMRs	# rRNAs	# Plasmid Hits
contig54|Assembly_SPAdes|R15.0599	4872	NA	6	12.3	no	0	0	0	0	0	3	0	1
contig55|Assembly_SPAdes|R15.0599	4640	NA	5	14.4	no	1	0	0	0	0	3	0	1
```

Best reagards!

**Comment by chen1i6c04** [comment]
It can work. Thanks very much.
