### ISSUE TITLE
automatically recognise db_path with conda installation

### ISSUE THREAD

**Issue by noeldjitro** [oschwengers/platon#9]
Hi,
this is just a note.

To make platon recognize the db_path without specify the '--db' with conda installation, I put the db folder in
~/miniconda3/envs/envs_name/lib/python3.8/site-packages

Cheers

**Comment by oschwengers** [comment]
Hi @noeldjitro ,
thanks for the note. I haven't fiddled around too much with an automatic download/installation procedure for the database. I might put this on my list for future enhancements if this is of interest for more users.
I'll close this issue for now but labeled it for a future recognition.

Best regards!
